FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci --only=production
COPY frontend/.next ./.next
COPY frontend/public ./public
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start"]
